defmodule Atomboy.CPU.Table do
  @moduledoc """
  The SM83's instruction table, as data.

  This is the only file to edit in order to add a family of opcodes. It contains
  no executable code, no AST manipulation, no calling convention: only the
  description of what the processor does. `Atomboy.CPU.Gen` translates,
  `Atomboy.CPU` hosts the clauses.

  ## The octal decomposition

  The SM83 table is regular once you read the opcode byte as three fields:
  `x` (bits 7-6), `y` (bits 5-3), `z` (bits 2-0).

      x=0  → assorted operations, regular in (y, z)
      x=1  → LD r, r'  over 0x40-0x7F, except 0x76 which HALT requisitioned
      x=2  → ALU A, r  — 8 operations × 8 sources
      x=3  → jumps, stack, calls

  Hence families generated by comprehension rather than 500 lines copied out by
  hand. A flag fix then happens in a single place, and the silent typos — the
  ones the test vectors cannot always tell apart from a real bug — have nowhere
  left to hide.
  """

  alias Atomboy.CPU.Insn

  # The 3-bit `r` encoding, shared by the whole table. 6 means (HL).
  @r {:b, :c, :d, :e, :h, :l, :hl_ind, :a}

  @doc "The operand denoted by a 3-bit `r` field."
  @spec operand(0..7) :: Insn.operand()
  def operand(6), do: :hl_ind
  def operand(index), do: {:reg, elem(@r, index)}

  @doc """
  The base table, unprefixed.
  """
  @spec base() :: [Insn.t()]
  def base do
    misc() ++
      indirect_block() ++
      jr_block() ++
      acc_block() ++
      stack_block() ++
      jump_block() ++
      alu_imm_block() ++
      pair_block() ++ inc_dec_block() ++ load_imm8_block() ++ load_block() ++ alu_block()
  end

  @doc """
  The extended table, prefixed by 0xCB — the more regular of the two.

  x=0: eight rotations/shifts over the eight targets; x=1/2/3: BIT, RES and SET,
  with the bit number in the y field. The (HL) forms pay for the
  read-modify-write (16 T), except BIT which only reads (12 T). The cycle counts
  include fetching the prefix.
  """
  @cb_rots {:rlc, :rrc, :rl, :rr, :sla, :sra, :swap, :srl}

  @spec extended() :: [Insn.t()]
  def extended do
    rotations =
      for y <- 0..7, z <- 0..7 do
        %Insn{
          prefix: :cb,
          opcode: y * 8 + z,
          mnemonic: elem(@cb_rots, y),
          operands: [operand(z)],
          cycles: if(z == 6, do: 16, else: 8)
        }
      end

    bit_ops =
      for {mnemonic, x} <- [bit: 0x40, res: 0x80, set: 0xC0], y <- 0..7, z <- 0..7 do
        %Insn{
          prefix: :cb,
          opcode: x + y * 8 + z,
          mnemonic: mnemonic,
          operands: [{:bit, y}, operand(z)],
          cycles:
            cond do
              z != 6 -> 8
              mnemonic == :bit -> 12
              true -> 16
            end
        }
      end

    rotations ++ bit_ops
  end

  @doc "Every described instruction, all prefixes together."
  @spec all() :: [Insn.t()]
  def all, do: base() ++ extended()

  # ── x=0 ─────────────────────────────────────────────────────────────────────

  defp misc do
    [
      %Insn{opcode: 0x00, mnemonic: :nop, cycles: 4},
      # STOP — actually stopping waits for the clock controller. The hardware
      # encodes it over two bytes, but the SingleStepTests corpus models it as
      # one, at 12 T-cycles: we follow the corpus, which is this phase's oracle.
      # To revisit when STOP really does something.
      %Insn{opcode: 0x10, mnemonic: :stop, cycles: 12},
      # LD (a16), SP — the instruction set's only direct 16-bit write.
      %Insn{opcode: 0x08, mnemonic: :ld, operands: [:a16_ind, {:pair, :sp}], cycles: 20},
      # HALT: 12 T in the corpus's model, like STOP.
      %Insn{opcode: 0x76, mnemonic: :halt, cycles: 12},
      %Insn{opcode: 0xF3, mnemonic: :di, cycles: 4},
      # EI: the enable is deferred by one instruction — the corpus checks this
      # (ime unchanged on the EI's own step). See ime_pending.
      %Insn{opcode: 0xFB, mnemonic: :ei, cycles: 4},
      %Insn{opcode: 0xF9, mnemonic: :ld, operands: [{:pair, :sp}, {:pair, :hl}], cycles: 8},
      %Insn{opcode: 0xE8, mnemonic: :add_sp, operands: [{:pair, :sp}, {:imm, 8}], cycles: 16},
      %Insn{opcode: 0xF8, mnemonic: :add_sp, operands: [{:pair, :hl}, {:imm, 8}], cycles: 12},
      # The 0xFF00 high page — the I/O registers. LDH through an immediate byte,
      # or through C.
      %Insn{opcode: 0xE0, mnemonic: :ldh, operands: [:a8_ind, {:reg, :a}], cycles: 12},
      %Insn{opcode: 0xF0, mnemonic: :ldh, operands: [{:reg, :a}, :a8_ind], cycles: 12},
      %Insn{opcode: 0xE2, mnemonic: :ldh, operands: [:c_ind, {:reg, :a}], cycles: 8},
      %Insn{opcode: 0xF2, mnemonic: :ldh, operands: [{:reg, :a}, :c_ind], cycles: 8},
      %Insn{opcode: 0xEA, mnemonic: :ld, operands: [:a16_ind, {:reg, :a}], cycles: 16},
      %Insn{opcode: 0xFA, mnemonic: :ld, operands: [{:reg, :a}, :a16_ind], cycles: 16}
    ]
  end

  # ── x=0, z=2: indirect LDs between A and the pairs ──────────────────────────
  #
  # q=0 writes A to memory, q=1 reads it. The HL+ and HL- forms post-adjust HL
  # after the access — the two encodings the AF pair would have taken.

  @indirects [{0x02, :bc}, {0x12, :de}, {0x22, :hl_inc}, {0x32, :hl_dec}]

  defp indirect_block do
    stores =
      for {opcode, target} <- @indirects do
        %Insn{opcode: opcode, mnemonic: :ld, operands: [{:ind, target}, {:reg, :a}], cycles: 8}
      end

    loads =
      for {opcode, target} <- @indirects do
        %Insn{
          opcode: opcode + 8,
          mnemonic: :ld,
          operands: [{:reg, :a}, {:ind, target}],
          cycles: 8
        }
      end

    stores ++ loads
  end

  # ── x=0, z=0: JR ────────────────────────────────────────────────────────────
  #
  # Relative jump, one signed byte of offset. The conditional forms cost
  # 12 T-cycles taken, 8 untaken — the first place where the table describes
  # behaviour that depends on execution.

  defp jr_block do
    unconditional = %Insn{opcode: 0x18, mnemonic: :jr, operands: [{:imm, 8}], cycles: 12}

    conditionals =
      for {condition, index} <- [nz: 0, z: 1, nc: 2, c: 3] do
        %Insn{
          opcode: 0x20 + index * 8,
          mnemonic: :jr,
          operands: [{:imm, 8}],
          condition: condition,
          cycles: 12,
          cycles_untaken: 8
        }
      end

    [unconditional | conditionals]
  end

  # ── x=0, z=7: operations on the accumulator ─────────────────────────────────
  #
  # Eight instructions with no explicit operand — A and F are implicit. The order
  # of the `y` field is the silicon's.

  @acc_ops {:rlca, :rrca, :rla, :rra, :daa, :cpl, :scf, :ccf}

  defp acc_block do
    for y <- 0..7 do
      %Insn{opcode: y * 8 + 0x07, mnemonic: elem(@acc_ops, y), cycles: 4}
    end
  end

  # ── x=0: the 16-bit pairs ───────────────────────────────────────────────────
  #
  # The `p` field (bits 5-4) names the pair: BC, DE, HL, SP. Four families over
  # the low columns: LD rr, d16 (z=1, q=0), ADD HL, rr (z=1, q=1), INC rr
  # (z=3, q=0), DEC rr (z=3, q=1).

  @pairs {:bc, :de, :hl, :sp}

  defp pair(index), do: {:pair, elem(@pairs, index)}

  defp pair_block do
    for p <- 0..3 do
      [
        %Insn{opcode: p * 16 + 0x01, mnemonic: :ld, operands: [pair(p), {:imm, 16}], cycles: 12},
        %Insn{
          opcode: p * 16 + 0x09,
          mnemonic: :add,
          operands: [{:pair, :hl}, pair(p)],
          cycles: 8
        },
        # 16-bit INC/DEC: no flag touched — unlike their 8-bit namesakes, and it
        # is the hardware that wants it that way.
        %Insn{opcode: p * 16 + 0x03, mnemonic: :inc, operands: [pair(p)], cycles: 8},
        %Insn{opcode: p * 16 + 0x0B, mnemonic: :dec, operands: [pair(p)], cycles: 8}
      ]
    end
    |> List.flatten()
  end

  # ── x=0, z=4/z=5: INC r / DEC r ─────────────────────────────────────────────
  #
  # The target sits in the `y` field. The (HL) form is a read-modify-write:
  # 12 T-cycles (fetch, read, write) against 4 for a register.

  defp inc_dec_block do
    for {mnemonic, z} <- [inc: 4, dec: 5], target <- 0..7 do
      %Insn{
        opcode: target * 8 + z,
        mnemonic: mnemonic,
        operands: [operand(target)],
        cycles: if(target == 6, do: 12, else: 4)
      }
    end
  end

  # ── x=0, z=6: LD r, d8 ──────────────────────────────────────────────────────
  #
  # The destination sits in the `y` field, the immediate follows the opcode. The
  # first block with a multi-byte operand: PC advances by two in total.

  defp load_imm8_block do
    for dst <- 0..7 do
      %Insn{
        opcode: dst * 8 + 0x06,
        mnemonic: :ld,
        operands: [operand(dst), {:imm, 8}],
        # Opcode fetch, immediate fetch — plus the memory write for
        # LD (HL), d8.
        cycles: if(dst == 6, do: 12, else: 8)
      }
    end
  end

  # ── x=3: the stack ──────────────────────────────────────────────────────────
  #
  # The stack pairs swap SP for AF — pushing SP onto itself would make no sense.
  # PUSH costs one M-cycle more than POP: the hardware decrements SP before
  # writing, and that decrement has a cycle of its own.

  @stack_pairs {:bc, :de, :hl, :af}

  defp stack_block do
    for p <- 0..3 do
      pair = {:pair, elem(@stack_pairs, p)}

      [
        %Insn{opcode: 0xC1 + p * 16, mnemonic: :pop, operands: [pair], cycles: 12},
        %Insn{opcode: 0xC5 + p * 16, mnemonic: :push, operands: [pair], cycles: 16}
      ]
    end
    |> List.flatten()
  end

  # ── x=3: absolute jumps, calls, returns ─────────────────────────────────────
  #
  # The four conditions share the y-field encoding with JR. The taken/untaken
  # costs differ by family: the gap is the work genuinely skipped — the operand
  # read already done for JP (16/12), the stack left alone for CALL (24/12), the
  # stack read avoided for RET (20/8).

  @conditions [nz: 0, z: 1, nc: 2, c: 3]

  defp jump_block do
    jp =
      [
        %Insn{opcode: 0xC3, mnemonic: :jp, operands: [{:imm, 16}], cycles: 16},
        # JP HL — often written "JP (HL)", but there is no memory access at all:
        # PC receives the pair, that is all. The computed jump the future
        # trampoline will use.
        %Insn{opcode: 0xE9, mnemonic: :jp, operands: [{:pair, :hl}], cycles: 4}
      ] ++
        for {condition, index} <- @conditions do
          %Insn{
            opcode: 0xC2 + index * 8,
            mnemonic: :jp,
            operands: [{:imm, 16}],
            condition: condition,
            cycles: 16,
            cycles_untaken: 12
          }
        end

    call =
      [%Insn{opcode: 0xCD, mnemonic: :call, operands: [{:imm, 16}], cycles: 24}] ++
        for {condition, index} <- @conditions do
          %Insn{
            opcode: 0xC4 + index * 8,
            mnemonic: :call,
            operands: [{:imm, 16}],
            condition: condition,
            cycles: 24,
            cycles_untaken: 12
          }
        end

    ret =
      [
        %Insn{opcode: 0xC9, mnemonic: :ret, cycles: 16},
        # RETI: RET + IME. The enable is immediate, unlike EI's one-instruction
        # delay.
        %Insn{opcode: 0xD9, mnemonic: :reti, cycles: 16}
      ] ++
        for {condition, index} <- @conditions do
          %Insn{
            opcode: 0xC0 + index * 8,
            mnemonic: :ret,
            condition: condition,
            cycles: 20,
            cycles_untaken: 8
          }
        end

    rst =
      for slot <- 0..7 do
        %Insn{opcode: 0xC7 + slot * 8, mnemonic: :rst, operands: [{:rst, slot * 8}], cycles: 16}
      end

    jp ++ call ++ ret ++ rst
  end

  # ── x=1: LD r, r' ───────────────────────────────────────────────────────────

  defp load_block do
    for dst <- 0..7, src <- 0..7, not (dst == 6 and src == 6) do
      %Insn{
        opcode: 0x40 + dst * 8 + src,
        mnemonic: :ld,
        operands: [operand(dst), operand(src)],
        # A memory access costs one M-cycle more, whichever side of the
        # assignment it is on. Both at once does not exist: `dst = src = 6`
        # would have been "LD (HL), (HL)", an encoding HALT requisitioned.
        cycles: if(dst == 6 or src == 6, do: 8, else: 4)
      }
    end
  end

  # ── x=2: ALU A, r ───────────────────────────────────────────────────────────

  # The eight operations, in `y`-field order. That order is not this project's
  # choice: it is the silicon's encoding.
  @alu {:add, :adc, :sub, :sbc, :and, :xor, :or, :cp}

  defp alu_imm_block do
    for y <- 0..7 do
      %Insn{
        opcode: 0xC6 + y * 8,
        mnemonic: elem(@alu, y),
        operands: [{:reg, :a}, {:imm, 8}],
        cycles: 8
      }
    end
  end

  defp alu_block do
    for y <- 0..7, z <- 0..7 do
      %Insn{
        opcode: 0x80 + y * 8 + z,
        mnemonic: elem(@alu, y),
        # A appears explicitly as the first operand of all eight, including the
        # ones the assembler writes without mentioning it (`SUB B`, `AND B`). A
        # really is read and — except for CP — written; leaving it out would make
        # the table irregular where the processor is not.
        operands: [{:reg, :a}, operand(z)],
        cycles: if(z == 6, do: 8, else: 4)
      }
    end
  end
end
