/* The Game Boy, on the silicon.
 *
 * Everything below the calling convention is generated by `lib/atomboy/native/`
 * and emitted as RV32I by Elixir: the 501 opcode handlers, the ALU's flag
 * arithmetic, the DMG scanline renderer, the 154-line frame cadence, the
 * cartridge's bank switching. None of it knows this file exists, and this file
 * knows none of it -- the whole seam is a pointer in and a pointer out.
 *
 *     uint32_t entry(void *argument)
 *
 * What comes back points at five words: status, the opcode it stopped on,
 * T-cycles run, the framebuffer, and the emulated 64 KB.
 *
 * The proof this run is after is not a picture. It is a checksum: the same ten
 * frames of games/hero.gb, run by the BEAM emulator on a laptop and by this
 * blob on a C6, have to come out bit for bit identical. The panel comes after,
 * and it comes after on purpose -- pixels one already trusts are the only kind
 * worth debugging an SPI bus with.
 */

#include <stdio.h>
#include <string.h>

#include "esp_cpu.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "esp_rom_crc.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

static const char *TAG = "atomboy";

/* Placed by EMBED_FILES: the blob lives in flash and is copied into RAM. */
extern const uint8_t blob_start[] asm("_binary_blob_bin_start");
extern const uint8_t blob_end[] asm("_binary_blob_bin_end");

#define FRAMES 10
#define FRAME_BYTES (160 * 144)

/* What the Elixir suite pins for hero.gb's tenth frame. Same constant, same
 * meaning: test/native_machine_test.exs, @hero_crc. */
#define HERO_CRC 0x5AA2E5B7u

struct result {
  uint32_t status;
  uint32_t opcode;
  uint32_t cycles;
  uint32_t framebuffer;
  uint32_t memory;
};

typedef uint32_t (*atomboy_entry_t)(void *argument);

void app_main(void) {
  const size_t size = (size_t)(blob_end - blob_start);

  ESP_LOGI(TAG, "blob: %u bytes of generated RV32I, code and data", (unsigned)size);

  /* Internal RAM, word aligned, and executable because sdkconfig.defaults takes
   * the PMP split off -- the C6's HP SRAM answers to both buses at one address,
   * but ESP-IDF marks the data half non-executable unless told otherwise. */
  void *executable = heap_caps_aligned_alloc(4, size, MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);

  if (executable == NULL) {
    ESP_LOGE(TAG, "no executable memory: %u bytes refused", (unsigned)size);
    return;
  }

  memcpy(executable, blob_start, size);

  /* Written through the data bus, about to be fetched through the instruction
   * one. Without the fence the processor may run whatever was there before. */
  __asm__ volatile("fence.i" ::: "memory");

  ESP_LOGI(TAG, "entry at %p, running %d frames of hero.gb", executable, FRAMES);

  const uint32_t before = esp_cpu_get_cycle_count();
  const uint32_t returned = ((atomboy_entry_t)executable)(NULL);
  const uint32_t after = esp_cpu_get_cycle_count();

  const struct result *result = (const struct result *)returned;

  if (result->status != 0) {
    ESP_LOGE(TAG, "stopped on an opcode it does not know: 0x%02lx", result->opcode);
    return;
  }

  const uint32_t crc = esp_rom_crc32_le(0, (const uint8_t *)result->framebuffer, FRAME_BYTES);

  ESP_LOGI(TAG, "frame CRC 0x%08lX -- the BEAM emulator says 0x%08X", crc, HERO_CRC);

  if (crc == HERO_CRC) {
    ESP_LOGI(TAG, "IDENTICAL: the same pixels, on a laptop and on this chip");
  } else {
    ESP_LOGE(TAG, "DIVERGENT: the chip drew something else");
  }

  /* The measurement qemu could never give. Everything until now has been
   * retired instructions; this is cycles, on silicon, with the flash latency
   * and the cache misses and the branch predictor all included. */
  const uint32_t cycles = after - before;
  const uint32_t per_frame = cycles / FRAMES;
  const uint32_t hz = 160000000u;

  ESP_LOGI(TAG, "%lu CPU cycles for %d frames -- %lu per frame", cycles, FRAMES, per_frame);
  ESP_LOGI(TAG, "%lu us per frame, so %lu%% of a 60 fps budget", per_frame / (hz / 1000000u),
           (per_frame * 60u) / (hz / 100u));
  ESP_LOGI(TAG, "emulated T-cycles: %lu", result->cycles);

  while (1) {
    vTaskDelay(pdMS_TO_TICKS(1000));
  }
}
