/* First light: does Elixir-emitted RV32 run on the silicon?
 *
 * The whole native core is generated by `lib/atomboy/native/` and has, until
 * now, only ever run under qemu's `virt` board -- where it boots the machine
 * itself, drives a 16550 UART and powers off through `sifive_test`. None of
 * that exists here. On the C6 an application is already running, and what it
 * wants from the emulator is a subroutine.
 *
 * So the blob is a function. This file is the smallest possible proof that the
 * arrangement holds: copy the bytes somewhere executable, call offset 0, and
 * check what comes back. It computes 1+2+...+100, because a blob that returned
 * a constant could not be told from a register that happened to hold it.
 *
 * The blob is position independent -- addresses are built with `auipc` -- so
 * nothing here has to care where the allocator put it.
 */

#include <stdio.h>
#include <string.h>

#include "esp_cpu.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "blob.h"

static const char *TAG = "atomboy";

typedef uint32_t (*atomboy_entry_t)(void *argument);

void app_main(void) {
  ESP_LOGI(TAG, "blob: %d bytes of generated RV32I", ATOMBOY_BLOB_SIZE);

  /* Internal RAM, word aligned. On the C6 that is already executable memory:
   * the HP SRAM answers to both the instruction and the data bus at the same
   * address, so there is no separate exec heap to ask for -- MALLOC_CAP_EXEC
   * is not a registered capability here and returns NULL. What does stand in
   * the way is the PMP split ESP-IDF installs at startup, which is why
   * sdkconfig.defaults turns it off. */
  void *executable =
      heap_caps_aligned_alloc(4, ATOMBOY_BLOB_SIZE, MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);

  if (executable == NULL) {
    ESP_LOGE(TAG, "no executable memory: %d bytes refused", ATOMBOY_BLOB_SIZE);
    return;
  }

  memcpy(executable, atomboy_blob, ATOMBOY_BLOB_SIZE);

  /* The bytes were written through the data bus and are about to be fetched
   * through the instruction one. Anything stale in between is a jump into
   * whatever was there before. */
  __asm__ volatile("fence.i" ::: "memory");

  ESP_LOGI(TAG, "entry at %p, calling", executable);

  atomboy_entry_t entry = (atomboy_entry_t)executable;
  uint32_t result = entry(NULL);

  if (result == ATOMBOY_BLOB_EXPECTS) {
    ESP_LOGI(TAG, "OK -- returned %lu, which is what it had to compute", result);
  } else {
    ESP_LOGE(TAG, "returned %lu, expected %u", result, ATOMBOY_BLOB_EXPECTS);
  }

  heap_caps_free(executable);

  while (1) {
    vTaskDelay(pdMS_TO_TICKS(1000));
  }
}
