defmodule Atomboy.AtomVM.Smoke do
  @moduledoc """
  The entry point of the AtomVM guardrail. See `mix help atomboy.atomvm`.

  This module does not test the CPU's correctness — that is the job of the SM83
  vectors, on standard OTP where debugging is possible. It answers a single
  question: **does the compiled code load and run under AtomVM?**

  What breaks at this level is invisible on the Mac: a BEAM instruction missing
  from AtomVM's table, an unimplemented OTP function, an Elixir construct that
  assumes a complete standard library. Finding that out in phase 2, with weeks
  of code written on top, is expensive — hence a runnable check from the very
  first module.

  The program it exercises goes through the mechanisms that matter: the dense
  integer dispatch generated by `for`, the `Bitwise` operations, the map NIF
  call, and tuple construction.
  """

  @program %{
    # LD B, C     — register to register
    0x0000 => 0x41,
    # LD (HL), B  — memory write
    0x0001 => 0x70,
    # LD A, (HL)  — memory read
    0x0002 => 0x7E,
    # NOP
    0x0003 => 0x00
  }

  @doc """
  AtomVM entry point. Prints `smoke ok`, or the detail of the discrepancy.
  """
  def start do
    mem = Atomboy.Memory.Flat.new(@program)
    state = %Atomboy.CPU.State{c: 0x42, h: 0xC0, sp: 0xFFFE}

    {final, mem, cycles} = run(state, mem, 4, 0)

    checks = [
      {:b, final.b, 0x42},
      {:a, final.a, 0x42},
      {:pc, final.pc, 0x0004},
      {:mem_c000, Atomboy.Memory.Flat.read8(mem, 0xC000), 0x42},
      {:cycles, cycles, 4 + 8 + 8 + 4}
    ]

    case Enum.reject(checks, fn {_name, got, want} -> got == want end) do
      [] ->
        :erlang.display(:smoke_ok)

      bad ->
        :erlang.display(:smoke_failed)

        Enum.each(bad, fn {name, got, want} -> :erlang.display({name, :got, got, :want, want}) end)
    end

    0
  end

  defp run(state, mem, 0, cycles), do: {state, mem, cycles}

  defp run(state, mem, steps, cycles) do
    {state, mem, step_cycles} = Atomboy.CPU.step(state, mem)
    run(state, mem, steps - 1, cycles + step_cycles)
  end
end
